trigger:
  batch: true
  branches:
    include:
    - '*'
  paths:
    exclude:
      - README.md
      - LICENSE
      - .github
stages:

- stage: onRelease
  variables:
    - group: releaseVariables
  condition: |
    eq(variables['Build.SourceBranch'], 'refs/heads/qa')
  jobs:
  - job: onReleaseJob
    pool:
      vmImage: 'ubuntu-22.04'

    steps:
    - script: env | sort
      displayName: 'Environment / Context'
    
    - task: UsePythonVersion@0
      displayName: 'Use Python 3.8'
      inputs:
        versionSpec: 3.8
    
    - task: AzureCLI@2
      inputs:
        azureSubscription: spconnection
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          echo "Getting access token..."
          DATABRICKS_TOKEN=$(az account get-access-token --resource 2ff814a6-3304-4ab8-85cb-cd0e6f879c1d --query "accessToken" -o tsv)
          echo "##vso[task.setvariable variable=DATABRICKS_TOKEN]$DATABRICKS_TOKEN"
        
    
    - checkout: self
      displayName: 'Checkout & Build.Reason: $(Build.Reason) & Build.SourceBranchName: $(Build.SourceBranchName)'

    - script: |
            # this is because of the old dependency inside Nutter
            python -m pip install --upgrade pip nutter
            python -m pip install wheel
            python -m pip install setuptools
            python -m pip install pytest
            python -m pip install pyspark
      displayName: 'Install dependencies' 
      
    - script: |
        echo Instalando o CLI do Databricks...
        curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
      displayName: 'Instalar CLI do Databricks'
    
    - script: |
        echo Configurando o CLI do Databricks...
        databricks configure --token
        echo -e "[DATABRICKS_HOST]\n[DATABRICKS_TOKEN]" | databricks configure --token
      env:
        DATABRICKS_HOST: $(DATABRICKS_HOST)
        DATABRICKS_TOKEN: $(DATABRICKS_TOKEN)
      displayName: 'Configurar CLI do Databricks'
    - script: databricks bundle validate -t $(env)
      workingDirectory: $(System.DefaultWorkingDirectory)/awesome-bundle
      displayName: Validate bundle for $(env) enviroment

    - script: |
        echo Deploy do bundle via CLI do Databricks...
        databricks bundle deploy -t $(env)
      workingDirectory: $(System.DefaultWorkingDirectory)/awesome-bundle
      displayName: Deploy job on $(env) enviroment

      
- stage: toProduction
  variables:
    - group: PrdVariables
  condition: |
    eq(variables['Build.SourceBranch'], 'refs/heads/main')
  dependsOn: onRelease
  jobs:
  - job: onReleaseJob
    pool:
      vmImage: 'ubuntu-22.04'

    steps:
    - script: env | sort
      displayName: 'Environment / Context'

    - task: UsePythonVersion@0
      displayName: 'Use Python 3.8'
      inputs:
        versionSpec: 3.8

    - checkout: self
      persistCredentials: true
      clean: true
      displayName: 'Checkout & Build.Reason: $(Build.Reason) & Build.SourceBranchName: $(Build.SourceBranchName)'

    - task: AzureCLI@2
      inputs:
        azureSubscription: spconnection
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          echo "Getting access token..."
          DATABRICKS_TOKEN=$(az account get-access-token --resource 2ff814a6-3304-4ab8-85cb-cd0e6f879c1d --query "accessToken" -o tsv)
          echo "##vso[task.setvariable variable=DATABRICKS_TOKEN]$DATABRICKS_TOKEN"

    - script: |
          python -m pip install --upgrade pip nutter
          # this is because of the old dependency inside Nutter
          python -m pip install wheel
          python -m pip install setuptools
      displayName: 'Install dependencies' 

    - script: |
        echo Instalando o CLI do Databricks...
        curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
      displayName: 'Instalar CLI do Databricks'
    
    - script: |
        echo Configurando o CLI do Databricks...
        databricks configure --token
        echo -e "[DATABRICKS_HOST]\n[DATABRICKS_TOKEN]" | databricks configure --token
      env:
        DATABRICKS_HOST: $(DATABRICKS_HOST)
        DATABRICKS_TOKEN: $(DATABRICKS_TOKEN)
      displayName: 'Configurar CLI do Databricks'

    - script: |
        databricks bundle validate -t $(env)
      workingDirectory: $(System.DefaultWorkingDirectory)/awesome-bundle
      displayName: Validate bundle for $(env) enviroment
      

    - script: |
        echo Deploy do bundle via CLI do Databricks...
        databricks bundle deploy -t $(env) 
      workingDirectory: $(System.DefaultWorkingDirectory)/awesome-bundle
      displayName: Deploy job on $(env) enviroment